### ISSUE TITLE
[React v15] Accessing PropTypes via the main React package is deprecated

### ISSUE THREAD

**Issue by rzymek** [xeodou/react-crouton#14]
After upgrading to react 15.5.4 I'm getting these warnings in the browser console:

> Warning: Accessing PropTypes via the main React package is deprecated. Use the prop-types package from npm instead.
>warning.js:36 Warning: react-crouton: React.createClass is deprecated and will be removed in version 16. Use plain JavaScript classes instead. If you're not yet ready to migrate, create-react-class is available on npm as a drop-in replacement.

**Comment by xeodou** [comment]
hmm, i'll do an update to fix it.  But it should be fine with v15, since it will be remove from v16

**Comment by xeodou** [comment]
1.0.0 is released to support `prop-types', closed. 
Thank @larsmaultsby
