### ISSUE TITLE
Update react version?

### ISSUE THREAD

**Issue by slnowak** [xeodou/react-crouton#3]
I'm trying to use your component altogether with react-bootstrap, but while installing dependencies I'm seeing this:

39251 error peerinvalid The package react does not satisfy its siblings' peerDependencies requirements!
39251 error peerinvalid Peer react-bootstrap@0.20.3 wants react@>=0.13
39251 error peerinvalid Peer react-crouton@0.2.3 wants react@0.12.x

Is it possible to upgrade react version in your dependencies?

**Comment by xeodou** [comment]
Sure, I will have a test and upgrade it today.

**Comment by xeodou** [comment]
@slnowak I have push a new version `react-crouton@0.2.4`, you can try again.

**Comment by slnowak** [comment]
Thanks, everything works fine now.
