### ISSUE TITLE
onDismiss called immediately

### ISSUE THREAD

**Issue by Laoujin** [xeodou/react-crouton#5]
The tests are failing for me but this is the test:

Create a new Crouton and check that the onDismiss function is not called before the timeout has expired.

```
it('should not call onDismiss directly', function() {
    var dismissCalled = 0;
    var crouton = TestUtils.renderIntoDocument(
      Crouton({
        id: 123456,
        message: 'data.message',
        type: 'errorClassName',
        hidden: false,
        onDismiss: function() {
          dismissCalled++;
        }
      }))

      expect(dismissCalled, 0)
  })
```

At the moment this test would fail because `index.js::changeState` is called from `componentWillMount` where this line is executed:
```
this.dismiss();
```

Solutions?  
- Uncomment the line? The dismiss should be called (eventually) due the setTimeout
- Do not call `changeState` from `componentWillMount` but instead use `getInitialState` and `getDefaultProps` for the 'startup' logic

**Comment by xeodou** [comment]
@Laoujin I have remove `this.dismiss()` , I think this will works with you and already publish to npm.  
You can upgrade and try.
